### PR TITLE
Class building - DNM

### PR DESCRIPTION
**Pull request by vladd-png**
Create a basic outline for each class based on notes made in class.
User class has 3 key properties in a constructor and 2 methods.
Recipe class has 4 key properties in a constructor and 4 methods.
Ingredient class has 3 key properties in a constructor and 0 methods. 
Pantry class has 2 key properties in a constructor and 3 methods.

### CODE REVIEW

**Comment by vladd-png** [comment]
[Build out User Class](https://trello.com/c/Sn9b2yGs/5-build-out-user-class)

**Comment by vladd-png** [comment]
[Build out Ingredient Class](https://trello.com/c/TJyBffMX/7-build-out-ingredient-class)

**Comment by vladd-png** [comment]
[Build out Pantry Class](https://trello.com/c/Scy8ZgLN/8-build-out-pantry-class)

**Comment by vladd-png** [comment]
[Build out Recipe Class](https://trello.com/c/zfzscg3p/6-build-out-recipe-class)

**Review by jpweist — APPROVED** [review]
yea these are the classes we talked about

**Pull request merged**
